### ISSUE TITLE
自定义tab切换页

### ISSUE THREAD

**Issue by Moonlightg** [Moonlightg/mmp#69]
```html
<div class="head">
  <div class="content_tab">
    <div class="tab_left"><a href="javascript:;"> < </a></div>
    <div class="tab_right"><a href="javascript:;"> > </a></div>
    <ul id="tabs" class="list-tab">
      <li id="tab__manage_indexCenter" pid="_manage_indexCenter" data-index="_manage_indexCenter" class="cur">
        <a class="waves-effect waves-light">首页</a>
        <i class="tabs-close icon-close"></i>
      </li>
    </ul>
  </div>	
</div>
<section id="content">
  <div class="content_main">
    <div id="iframe__manage_indexCenter" class="iframe cur">	
      <ul>
        <li>
  	  <a href="javascript:Tab.addTab('tab页1', 'url1');">
  	    <p>tab页1</p> 
  	  </a>
        </li>
        <li>
  	  <a href="javascript:Tab.addTab('tab页2', 'url2');">
  	    <p>tab页2</p> 
  	  </a>
        </li>
        <li>
  	  <a href="javascript:Tab.addTab('tab页3', 'url3');">
  	    <p>tab页3</p> 
  	  </a>
        </li>
      </ul>
    </div>
  </div>
</section>
```

```js
<script type="text/javascript">
// ========== 选项卡操作 ==========js_jump
$(function() {
	// 选项卡点击
    $(document).on('click', '.content_tab li', function() {
        // 切换选项卡
        $('.content_tab li').removeClass('cur');
        $(this).addClass('cur');
        // 切换iframe
        $('.iframe').removeClass('cur');
        $('#iframe_' + $(this).data('index')).addClass('cur');
        var marginLeft = ($('#tabs').css('marginLeft').replace('px', ''));
        // 滚动到可视区域:在左侧
        if ($(this).position().left < marginLeft) {
            var left = $('.content_tab>ul').scrollLeft() + $(this).position().left - marginLeft;
            $('.content_tab>ul').animate({scrollLeft: left}, 200, function() {
                initScrollState();
            });
        }
        // 滚动到可视区域:在右侧
        if(($(this).position().left + $(this).width() - marginLeft) > document.getElementById('tabs').clientWidth) {
            var left = $('.content_tab>ul').scrollLeft() + (($(this).position().left + $(this).width() - marginLeft) - document.getElementById('tabs').clientWidth);
            $('.content_tab>ul').animate({scrollLeft: left}, 200, function() {
                initScrollState();
            });
        }
    });
 	// 控制选项卡滚动位置
    $(document).on('click', '.tab_left>a', function() {
        $('.content_tab>ul').animate({scrollLeft: $('.content_tab>ul').scrollLeft() - 300}, 200, function() {
            initScrollState();
        });
    });
    // 向右箭头
    $(document).on('click', '.tab_right>a', function() {
        $('.content_tab>ul').animate({scrollLeft: $('.content_tab>ul').scrollLeft() + 300}, 200, function() {
            initScrollState();
        });
    });
 	// 选项卡右上角关闭按钮
    $(document).on('click', '.tabs-close', function(event) {
        var obj = $(this).parent('li');
        var index = $(this).parent('li').data('index');
        if("_manage_indexCenter"!=index){
            Tab.closeTab(obj);
        }
        event.stopPropagation();
    });
});

// 选项卡对象
var Tab = {
    addTab: function(title, url) {
        // var index = url.replace(new RegExp('\\.','g'),'_');
        var index = url.replace(/\./g, '_').replace(/\//g, '_').replace(/:/g, '_').replace(/\?/g, '_').replace(/,/g, '_').replace(/=/g, '_').replace(/&/g, '_');
        // 如果存在选项卡，则激活，否则创建新选项卡
        if ($('#tab_' + index).length == 0) {
            // 添加选项卡
            $('.content_tab li').removeClass('cur');
            var tab = '<li id="tab_' + index +'" data-index="' + index + '" class="cur"><a class="waves-effect waves-light">' + title + '</a><i class="tabs-close icon-close"></i></li>';//<i class="zmdi zmdi-close"></i><
            $('.content_tab>ul').append(tab);
            // 添加iframe
            $('.iframe').removeClass('cur');
            var iframe = '<div id="iframe_' + index + '" class="iframe cur"><iframe class="tab_iframe" src="' + url + '" width="100%" frameborder="0" scrolling="auto" onload="changeFrameHeight(this)"></iframe></div>';
            $('.content_main').append(iframe);
            initScrollShow();
            $('.content_tab>ul').animate({scrollLeft: document.getElementById('tabs').scrollWidth - document.getElementById('tabs').clientWidth}, 200, function() {
                initScrollState();
            });
        } else {
            $('#tab_' + index).trigger('click');
        }
    },
    closeTab: function($item) {
        var closeable = $item.data('closeable');
        if (closeable != false) {
            // 如果当前时激活状态则关闭后激活左边选项卡
            if($item.hasClass('cur')) {
                $item.prev().trigger('click');
            }
            // 关闭当前选项卡
            var index = $item.data('index');
            $('#iframe_' + index).remove();
            $item.remove();
        }
        initScrollShow();
    }
}
function initScrollShow() {
    if (document.getElementById('tabs').scrollWidth > document.getElementById('tabs').clientWidth) {
        $('.content_tab').addClass('scroll');
    } else {
        $('.content_tab').removeClass('scroll');
    }
}
function initScrollState() {
    if ($('.content_tab>ul').scrollLeft() == 0) {
        $('.tab_left>a').removeClass('active');
    } else {
        $('.tab_left>a').addClass('active');
    }
    if (($('.content_tab>ul').scrollLeft() + document.getElementById('tabs').clientWidth) >= document.getElementById('tabs').scrollWidth) {
        $('.tab_right>a').removeClass('active');
    } else {
        $('.tab_right>a').addClass('active');
    }
}
// iframe高度自适应
function changeFrameHeight(ifm) {
    ifm.height = document.documentElement.clientHeight - 48;
}
</script>
```

```css
/* base */
body,html{ height:100%; }
body,html,ul,li,a{ padding: 0; margin: 0;}
body{ background: #e7e7e7;}
ul,li,a{ text-decoration: none; }
.head { display: flex; align-items: center; justify-content: space-between; height: 48px; line-height: 48px; padding: 0; background: #fff; border-bottom: 1px solid #eaeaea;}
/* tab */
.iframe { height: 100%; display: none;}
.content_main > .cur { display: block;}
.content_tab { width: 100%; height: 48px; overflow: hidden;}
.content_tab .list-tab { height: 70px;}
.content_tab > ul { padding: 0; font-size: 0; white-space: nowrap; -webkit-overflow-scrolling: touch;}
.scroll > ul { margin: 0 40px;}
.scroll > .tab_left,
.scroll > .tab_right { display: block;}
.tab_left,
.tab_right { width: 40px; height: 48px; line-height: 48px; color: #fff; text-align: center; display: none;}
.tab_left { float: left; margin-right: -40px;}
.tab_right { float: right; margin-left: -40px;}
.tab_left > a,
.tab_right > a { display: block; width: 100%; color: #254798; font-size: 16px;}
.tab_left > .active,
.tab_right > .active { color: #FF5722;}
.content_tab { position: relative;}
.content_tab > ul > li { position: relative; display: inline-block; height: 48px; line-height: 48px; margin: 0; font-size: 14px;}
.content_tab > ul > li:hover a { color: #000;}
.content_tab > ul > li:after,
.content_tab > ul > li:hover:after { background: #fbb157;}
.content_tab > ul > li > a { display: block; height: 48px; line-height: 48px; padding: 0 15px; transition: background-color 0.35s cubic-bezier(0.35, 0, 0.25, 1); border-bottom: none; position: relative;}
.content_tab > ul > li > a:active { background: rgba(255, 255, 255, 0.1);}
.content_tab > ul > .cur > a,
.content_tab > ul > .cur:hover > a { color: #f99b27;}
.content_tab > ul > li > a:after { content: ""; position: absolute; bottom: 0; left: 50%; right: 50%; border-bottom: 3px solid #f99b27; transition: all linear 0.2s;}
.content_tab > ul > .cur > a:after { right: 15px; left: 15px; bottom: 0; opacity: 1; transition: all linear 0.2s;}
.tabs-close { display: none; position: absolute; top: 3px; right: 3px; color: #fff; font-size: 12px; width: 10px; height: 10px; background: #f00;}
.list-tab { float: left; display: -webkit-box; display: -moz-box; display: -o-box; display: -ms-flexbox; display: -webkit-flex; display: -moz-flex; display: -ms-flex; display: -o-flex; display: flex; height: 50px; width: 93%; overflow: auto;}
.list-tab li { position: relative; display: inline-block; transform: translateZ(0); transition-property: color; transition-duration: .3s;}
.list-tab li a { display: block; padding: 0 15px; min-width: 50px; text-align: center;}
.list-tab li:after { content: ""; position: absolute; z-index: -1; left: 15px; right: 100%; bottom: 0; background: #0275d8; height: 3px; transition-property: right; transition-duration: .3s; transition-timing-function: ease-out;}
.list-tab li:hover { transition-duration: .3s; transition-property: color, background-color;}
.list-tab li:hover:after { right: 15px;}
.list-tab li.active { background: #6991e4;}
.list-tab li.active:after { right: 0;}
.content_tab > ul > li:hover .tabs-close { display: block;}
#tab__manage_indexCenter .tabs-close { display: none;}
```

![image](https://user-images.githubusercontent.com/14285531/45812207-b8551200-bd01-11e8-959c-33e3870ce1ec.png)
